export default {
  api: {
    output: {
      mode: "single",
      target: "src/api/internal-utils/autogenerated-api.ts",
      client: "react-query",
      prettier: true,
    },
    input: {
      target: "http://backend:8000/openapi.json",
    },
  },
};
