# fly.toml app configuration file generated for ai-calendar-backend on 2025-10-02T13:36:03+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ai-calendar-backend"

[build]
  dockerfile = "Dockerfile"

[env]
  # SQLite stored on a persistent volume mounted at /data
  DATABASE_URL = "sqlite:////data/database.db"

[[mounts]]
  source = "db_data"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
