import { User as UserDto } from "@/api/autogenerated-api"

export type User = {
  username: string
  lastLogin: Date | null
  isActive: boolean
}

function mapUser(dto: UserDto): User {
  return {
    username: dto.username,
    lastLogin: dto.last_login ? new Date(dto.last_login) : null,
    isActive: dto.is_active,
  }
}
