import { UserResponse, useCreateUser } from "@/api/autogenerated-api"
import { createMappedMutationHook } from "@/api/hook-factories"

export type User = {
  id: number
  username: string
  isActive: boolean
}

function mapUser(dto: UserResponse): User {
  return {
    id: dto.id,
    username: dto.username,
    isActive: dto.is_active,
  }
}

// TODO: Use factories.
// Wrap the Orval-generated mutation with a mapper and normaliser
export const useMappedCreateUserMutation = createMappedMutationHook(
  useCreateUser,
  mapUser
)
