name: Code Quality Checks

on:
  pull_request:
  push:
    branches:
      - dev
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          # Fallback keys if exact match isn't not found (searches for prefix).
          restore-keys: |
            pre-commit-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and cache pre-commit image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .dev-setup/Dockerfile
          tags: pre-commit-check
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run pre-commit checks
        run: |
            docker run --rm \
                -v ${{ github.workspace }}:/app \
                -v ~/.cache/pre-commit:/root/.cache/pre-commit \
                -w /app \
                pre-commit-check \
                pre-commit run --all-files --show-diff-on-failure --color always

      - name: Fix pre-commit cache permissions
        run: sudo chown -R $USER:$USER ~/.cache/pre-commit
