name: Code Quality Checks

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          # Fallback keys if exact match not found (searches for prefix).
          restore-keys: |
            pre-commit-

      - name: Build pre-commit image
        run: docker compose build pre-commit

      - name: Run pre-commit checks
        run: |
          docker compose run --rm \
            -v ~/.cache/pre-commit:/root/.cache/pre-commit \
            pre-commit run --all-files --show-diff-on-failure --color always
